name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    uses: yonatankarp/github-actions/.github/workflows/release-jar.yml@v2
    with:
      module-name: lib
      tag: ${{ github.event.release.tag_name }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
